CREATE TABLE IF NOT EXISTS files (
  id UUID PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  category VARCHAR(32) NOT NULL,
  reference_type VARCHAR(64) NOT NULL,
  reference_id VARCHAR(128) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(255),
  size BIGINT NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  data BYTEA NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(32),
  summary TEXT,
  tags TEXT,
  external_url TEXT,
  object_key VARCHAR(256),
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(128) NOT NULL UNIQUE,
  name VARCHAR(255),
  avatar_file_id UUID,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_login VARCHAR(128) NOT NULL UNIQUE,
  status VARCHAR(32) NOT NULL,
  granted_by VARCHAR(128),
  granted_at TIMESTAMP WITH TIME ZONE,
  revoked_by VARCHAR(128),
  revoked_at TIMESTAMP WITH TIME ZONE,
  remark TEXT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmap_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  parent_id BIGINT,
  title VARCHAR(255) NOT NULL,
  order_no INTEGER,
  resource_id BIGINT,
  note_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmap_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  user_key VARCHAR(128) NOT NULL,
  payload TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_roadmap_progress UNIQUE (roadmap_id, user_key)
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content_md TEXT NOT NULL,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  parent_id BIGINT,
  author_key VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  user_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  user_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type VARCHAR(32) NOT NULL,
  target_id BIGINT NOT NULL,
  reporter_key VARCHAR(128) NOT NULL,
  reason VARCHAR(255),
  details TEXT,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(128) NOT NULL,
  operator_key VARCHAR(128) NOT NULL,
  details TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key VARCHAR(128) NOT NULL,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  status VARCHAR(32) NOT NULL,
  file_id UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

INSERT INTO users (login, name, status, created_at, updated_at)
SELECT 'playwright-admin', 'Playwright Admin', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE login = 'playwright-admin');

INSERT INTO admin_accounts (user_login, status, granted_by, granted_at, remark, created_at, updated_at)
SELECT 'playwright-admin', 'ACTIVE', 'schema-test', CURRENT_TIMESTAMP, '测试管理员', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM admin_accounts WHERE user_login = 'playwright-admin');
