CREATE TABLE IF NOT EXISTS files (
  id UUID PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  category VARCHAR(32) NOT NULL,
  reference_type VARCHAR(64) NOT NULL,
  reference_id VARCHAR(128) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(255),
  size BIGINT NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  data BYTEA NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(32),
  summary CLOB,
  tags CLOB,
  external_url CLOB,
  object_key VARCHAR(256),
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(128) NOT NULL UNIQUE,
  name VARCHAR(255),
  bio CLOB,
  avatar_file_id UUID,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS admin_whitelist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  github_login VARCHAR(128) NOT NULL UNIQUE,
  role VARCHAR(32) NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description CLOB,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmap_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  parent_id BIGINT,
  title VARCHAR(255) NOT NULL,
  description CLOB,
  order_no INTEGER,
  resource_id BIGINT,
  note_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS roadmap_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  user_key VARCHAR(128) NOT NULL,
  payload CLOB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_roadmap_progress UNIQUE (roadmap_id, user_key)
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content_md CLOB NOT NULL,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  visibility VARCHAR(32),
  status VARCHAR(32),
  category VARCHAR(64),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  parent_id BIGINT,
  author_key VARCHAR(128) NOT NULL,
  content CLOB NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  user_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT,
  note_id BIGINT,
  user_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS note_view_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT NOT NULL,
  user_key VARCHAR(128) NOT NULL,
  viewed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_note_view_history_note_user UNIQUE (note_id, user_key)
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS bio CLOB;

ALTER TABLE notes
  ADD COLUMN IF NOT EXISTS category VARCHAR(64);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type VARCHAR(32) NOT NULL,
  target_id BIGINT NOT NULL,
  reporter_key VARCHAR(128) NOT NULL,
  reason VARCHAR(255),
  details CLOB,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(128) NOT NULL,
  operator_key VARCHAR(128) NOT NULL,
  details CLOB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key VARCHAR(128) NOT NULL,
  owner_key VARCHAR(128) NOT NULL DEFAULT 'local-dev-user',
  status VARCHAR(32) NOT NULL,
  file_id UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_files_roadmap_node_reference
  ON files(reference_type, reference_id, category, created_at);

CREATE INDEX IF NOT EXISTS idx_note_view_history_user_viewed_at
  ON note_view_history(user_key, viewed_at DESC);

CREATE INDEX IF NOT EXISTS idx_note_view_history_note_id
  ON note_view_history(note_id);

CREATE INDEX IF NOT EXISTS idx_notes_owner_category
  ON notes(owner_key, category);
