CREATE TABLE IF NOT EXISTS files (
  id UUID PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  category VARCHAR(32) NOT NULL,
  reference_type VARCHAR(64) NOT NULL,
  reference_id VARCHAR(128) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(255),
  size BIGINT NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  data BYTEA NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(32),
  summary CLOB,
  tags CLOB,
  external_url CLOB,
  object_key VARCHAR(256),
  visibility VARCHAR(32),
  status VARCHAR(32),
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);
